### PR TITLE
Hw6

### PR DESCRIPTION
**Pull request by AliyaMansurova**

### CODE REVIEW

**Review by loginov-rocks — CHANGES_REQUESTED** [review]
Meeting recap. If I not missed something:
- Integrate ESLint + AirBNB config
- Fix dev/runtime dependencies list
- Remove unnecessary async/await
- Implement seeding from the products file

**Comment by AliyaMansurova** [comment]
fixed

**Comment by loginov-rocks** [comment]
@AliyaMansurova I staged IntelliJ IDEA configuration containing code style options, feel free to adjust and commit them according to ESLint rules. I also switched some errors to the "warn" level.

I also integrated Husky for you to check if lint errors are present right before `git push`.

**Review by loginov-rocks — CHANGES_REQUESTED** [review]
@AliyaMansurova please ensure your code doesn't have ESLint errors, please run `npm run lint` in the project root. I see 70 problems: 49 errors and 30 warnings. You only required to fix errors to be able to pass this check.

**Comment by AliyaMansurova** [comment]
done

**Review by loginov-rocks — APPROVED** [review]
Great work!

**Pull request merged**
